{{- if and .Values.serviceAccount.create .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "policy-reporter-ui.labels" . | nindent 4 }}
  name: {{ include "policy-reporter-ui.fullname" . }}-secret-reader
rules:
- apiGroups: ['']
  resources:
  - secrets
  verbs:
  - get
{{- end -}}