name: sign
on:
  workflow_dispatch:
    inputs:
      ref:
        description: ref
        type: string
        required: true
      digest:
        description: digest
        type: string
        required: true

permissions:
  contents: read
  packages: write
  id-token: write 

jobs:
  push-policy-reporter-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - uses: CycloneDX/gh-gomod-generate-sbom@d4aee0cf5133055dbd98899978246c10c18c440f # v1.1.0
        with:
          version: v1

      - name: Generate SBOM
        run: |
          cd server
          ls -l
          go list -json -e .
          cyclonedx-gomod app -licenses -json -output policy-reporter-ui-bom.cdx.json

      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: policy-reporter-ui-bom-cdx
          path: policy-reporter-ui-bom.cdx.json

      - name: Install Cosign
        uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b # v2.8.1
        with:
          cosign-release: 'v1.13.0'

      - shell: bash
        env:
          COSIGN_EXPERIMENTAL: 'true'
          COSIGN_REPOSITORY: ghcr.io/kyverno/signatures
        run: |
          set -e
          cosign sign \
            -a "repo=${{ github.repository }}" \
            -a "workflow=${{ github.workflow }}" \
            -a "ref=${{ github.sha }}" \
            ghcr.io/kyverno/policy-reporter-ui@${{ inputs.digest }}
      
      - shell: bash
        env:
          COSIGN_REPOSITORY: ghcr.io/kyverno/sbom
        run: |
          cosign attach sbom --sbom ./policy-reporter-ui-bom.cdx.json --type cyclonedx ghcr.io/kyverno/policy-reporter-ui@${{ inputs.digest }}